### ISSUE TITLE
"Extended Barrel" results in both "Extended Barrel" and "Extended Mag"

### ISSUE THREAD

**Issue by 2bithacker** [48klocs/wish-list-magic-wand#21]
I noticed if you put "Extended Barrel" in the perks, the results will have rolls for both "Extended Barrel" (1467527085) and "Extended Mag" (2420895100), which doesn't seem like it should be intended.

![firefox_lEhaUY5J5a](https://github.com/48klocs/wish-list-magic-wand/assets/1847654/81e57a45-edd7-4f3a-9c05-273ea331edb3)

**Comment by 48klocs** [comment]
Sorry, just noticed this now. That's weird, I'll look in to it... soon.
